
find_path(CYRUS_SASL_INCLUDE_DIR
    NAMES sasl/sasl.h
    PATHS ${CONAN_INCLUDE_DIRS_CYRUS_SASL}
    NO_DEFAULT_PATH
)

find_library(CYRUS_SASL_LIBRARY
    NAMES sasl2
    PATHS ${CONAN_LIB_DIRS_CYRUS_SASL}
    NO_DEFAULT_PATH
)

if(CYRUS_SASL_INCLUDE_DIR)

    file(STRINGS ${PCRE_INCLUDE_DIR}/sasl/sasl.h DEFINE_CYRUS_SASL_MAJOR REGEX "^#define SASL_VERSION_MAJOR")
    string(REGEX REPLACE "^.*VERSION_MAJOR +([0-9]+).*$" "\\1" CYRUS_SASL_VERSION_MAJOR "${DEFINE_CYRUS_SASL_MAJOR}")

    file(STRINGS ${PCRE_INCLUDE_DIR}/sasl/sasl.h DEFINE_CYRUS_SASL_MINOR REGEX "^#define SASL_VERSION_MINOR")
    string(REGEX REPLACE "^.*VERSION_MINOR +([0-9]+).*$" "\\1" CYRUS_SASL_VERSION_MINOR "${DEFINE_CYRUS_SASL_MINOR}")

    file(STRINGS ${PCRE_INCLUDE_DIR}/sasl/sasl.h DEFINE_CYRUS_SASL_STEP REGEX "^#define SASL_VERSION_STEP")
    string(REGEX REPLACE "^.*VERSION_STEP +([0-9]+).*$" "\\1" CYRUS_SASL_VERSION_STEP "${DEFINE_CYRUS_SASL_STEP}")

    set(CYRUS_SASL_VERSION_STRING "${CYRUS_SASL_VERSION_MAJOR}.${CYRUS_SASL_VERSION_MINOR}.${CYRUS_SASL_VERSION_STEP}")
    set(CYRUS_SASL_VERSION ${PCRE_VERSION_STRING})
    set(CYRUS_SASL_VERSION_COUNT 3)

endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CYRUS_SASL
    REQUIRED_VARS CYRUS_SASL_INCLUDE_DIR CYRUS_SASL_LIBRARY
    VERSION_VAR CYRUS_SASL_VERSION
)

if(CYRUS_SASL_FOUND AND NOT TARGET CYRUS_SASL::CYRUS_SASL)

    add_library(CYRUS_SASL::CYRUS_SASL UNKNOWN IMPORTED)
    set_target_properties(CYRUS_SASL::CYRUS_SASL PROPERTIES
        IMPORTED_LOCATION ${CYRUS_SASL_LIBRARY}
        INTERFACE_INCLUDE_DIRECTORIES ${CYRUS_SASL_INCLUDE_DIR}
        INTERFACE_COMPILE_DEFINITIONS "${CONAN_COMPILE_DEFINITIONS_PCRE}"
    )

    mark_as_advanced(CYRUS_SASL_INCLUDE_DIR CYRUS_SASL_LIBRARY)

    set(CYRUS_SASL_INCLUDE_DIRS ${CYRUS_SASL_INCLUDE_DIR})
    set(CYRUS_SASL_LIBRARIES ${CYRUS_SASL_LIBRARY})
    set(CYRUS_SASL_DEFINITIONS "${CONAN_COMPILE_DEFINITIONS_CYRUS_SASL}")

endif()

